parameters:
    recruitis_api_url: 'https://app.recruitis.io/api2/'
    recruitis_api_token: '%env(RECRUITIS_API_TOKEN)%'
    cache_duration: 3600

services:
    # Default configuration for services
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Automatically register services in src/, except for exclusions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Register the Recruitis API service (fetches jobs from API)
    App\Model\Service\RecruitisApiService:
        arguments:
            $apiUrl: '%recruitis_api_url%'
            $apiToken: '%recruitis_api_token%'

    # Register the Job Cache Service (handles caching)
    App\Model\Service\JobCacheService:
        arguments:
            $cache: '@cache.app'
            $cacheDuration: '%cache_duration%'

    # Register the Job Service (orchestrates API and caching)
    App\Model\Service\JobService:
        arguments:
            $apiService: '@App\Model\Service\RecruitisApiService'
            $cacheService: '@App\Model\Service\JobCacheService'
